# GET http://localhost:8080/api/menu

# POST http://localhost:8080/api/menu
# content-type: application/json

# {
#     "label":"Burger",
#     "price":100000,
#     "description":"burger dari kerajaan"
# }


POST http://localhost:8080/api/submenu
content-type: application/json

{
    "menu_id":0,
    "label":"Burger Queen",
    "price":100000,
    "description":"burger dari kerajaan"
}