GET http://localhost:8080/api/menu

# PUT http://localhost:8080/api/menu/1
# content-type: application/json

# {
#     "price":100000
# }


POST http://localhost:8080/api/submenu
content-type: application/json

{
    "menu_id":1,
    "label":"Burger Queen",
    "price":100000,
    "description":"burger dari kerajaan"
}